[package]
name = "raytrascii"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rayon = "1.5.2"
ctrlc = { version = "3.2.2", features = ["termination"] }
terminal = { version = "0.2.1", features = ["crossterm-backend"] }
